# Lab 1: Introduction to Pytorch

This is the introduction to Pytorch.

This notebook contains `auto_grad` and

## Import modules

In [1]:
import torch

## Autograd Automatic Differentiation

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:

y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
# Note: `backward()` can be created only for scalar outputs
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [7]:
z = y.mean()
z.backward()

In [10]:
print(x.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


## Simple Neural Network